name: Build

on:
  workflow_dispatch:

jobs:
  mac_build:
    name: Build macOS binaries
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          choco install curl
          
      - name: Build binaries
        run: |
          cmake . -G "Unix Makefiles"
          make
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: daemon.exe
          path: daemon.exe
